version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=root
        - POSTGRES_DB=crud
    volumes:
        - "./crud-data:/var/lib/postgresql/data:rw"
    ports:
        - "5433:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
        - PGADMIN_DEFAULT_EMAIL=abdyworkin@gmail.com
        - PGADMIN_DEFAULT_PASSWORD=adminpassword
    ports:
        - "8080:80"