version: '3.8'

services:
    postgres:
        image: postgres:13
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root
            - POSTGRES_DB=crud
        volumes:
            - "./crud-data:/var/lib/postgresql/data:rw"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U root -d crud"]
            interval: 10s
            retries: 10
            start_period: 30s

    # pgadmin:
    #     image: dpage/pgadmin4
    #     environment:
    #         - PGADMIN_DEFAULT_EMAIL=admin@admin.com
    #         - PGADMIN_DEFAULT_PASSWORD=adminpassword
    #     ports:
    #         - "8080:80"

    app:
        build:
            context: .
            dockerfile: Dockerfile
        environment: 
            - DATABASE_URL=postgres://root:root@postgres:5432/crud?sslmode=disable

        ports:
            - "3000:3000"
        depends_on:
            postgres:
                condition: service_healthy